#!/bin/bash
DATAPATH=$(PWD)/data/wordpress/wp-content
if ! [ -d $DATAPATH ]; then
    logger -s "Creating $DATAPATH" 2>> $LOGFILE
    mkdir -p $DATAPATH
else
    echo "Found data directory: $DATAPATH"
fi
LOGFILE=$(PWD)/logs/$(date "+%Y%m%d_%H00").txt 
# log location for current container
logger -s "Will persist (latest) container app data @ $DATAPATH..." 2>> $LOGFILE

docker run --name wordpress-stg \
--link wp-mysql-stg:mysql \
-p 7300:80 \
-d uchilaka/wordpress:dev