#!/bin/bash
WDIR=$(pwd)
DATAPATH=$(pwd)/data/wordpress/wp-content
LOGFILE=$(pwd)/logs/$(date "+%Y%m%d_%H00").txt

# Include external variables 
$WDIR/private/vars

if ! [ -d $DATAPATH ]; then
    logger -s "Creating $DATAPATH" 2>> $LOGFILE
    mkdir -p $DATAPATH
else
    echo "Found data directory: $DATAPATH"
fi

# log location for current container
logger -s "Will persist (latest) container app data @ $DATAPATH..." 2>> $LOGFILE

# @IMPORTANT define the $MYSQL_... variables in private/vars. This WILL NOT exist in a 
# new deployment on the docker engine
docker run --name wordpress-stg \
-e WORDPRESS_DB_HOST=$MYSQL_HOST -e WORDPRESS_DB_NAME=$MYSQL_DB \
-e WORDPRESS_DB_USER=$MYSQL_USER -e WORDPRESS_DB_PASSWORD=$MYSQL_PWD \
-v $DATAPATH:/var/www/html/wp-content \
-p 7300:80 \
-d uchilaka/wordpress:dev